### ISSUE TITLE
dog has wrong hash on aarch64

### ISSUE THREAD

**Issue by nagy** [Mic92/nur-packages#12]
Currently, when trying to build `dog` i get:

```
hash mismatch in fixed-output derivation '/nix/store/k6f9alp4j3w5nii0b85xknb83qd1cbjy-dog-0.1.0-vendor.tar.gz':
  wanted: sha256:0q3jy8gykd7fhh4gdgfcbf30ksp78lq34pms6904c70skm6jnqck
  got:    sha256:1rjlcgcv8a627dm75h6f5md8dadj2p4s58cnf658d74g1fwh3xr5
cannot build derivation '/nix/store/52vlkw1hb6qkgl27rk9favyxzvb0hgps-dog-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/52vlkw1hb6qkgl27rk9favyxzvb0hgps-dog-0.1.0.drv' failed
```

Changing the hash locally fixed it and the package works fine.

**Comment by Mic92** [comment]
I just checked again. I still get the same checksum. What OS (release) are you using?

**Comment by Mic92** [comment]
You can also see that it works in CI: https://github.com/Mic92/nur-packages/runs/1375129911

**Comment by nagy** [comment]
I got this message on an ARM aarch64 machine ( RaspberryPi 4 ). But I just checked a x86_64 machine where it all works fine.

So it seems to download a different `dog-0.1.0-vendor.tar.gz` depending on the architecture.

**Comment by Mic92** [comment]
This is bad. Could you open a bug report in nixpkgs itself? This is a bug in `buildRustPackage` that needs to be addressed.

**Comment by nagy** [comment]
I tried on a different x86_64 machine and get the wrong hash again, so it looks like that it is not a problem of the architecture after all.
When comparing from your original archive to my mismatched archive I see this:
```diff
diff --git a/dog-0.1.0-vendor.tar.gz/.cargo/config b/dog-0.1.0-vendor.tar.gz/.cargo/config
index 392c555..785bed0 100755
--- a/dog-0.1.0-vendor.tar.gz/.cargo/config
+++ b/dog-0.1.0-vendor.tar.gz/.cargo/config
@@ -2,6 +2,7 @@
 "replace-with" = "vendored-sources"
 
 [source."https://github.com/llogiq/mutagen"]
+"branch" = "master"
 "git" = "https://github.com/llogiq/mutagen"
 "replace-with" = "vendored-sources"
```
Meaning that this one line got added to the archive. It might not be a problem in `buildRustPackage` after all. Potentially cargo creates these vendor packages on the fly and somethere a cdn might cache a different version of those files.

**Comment by Mic92** [comment]
@nagy do you use different nixpkgs versions for both machines? Maybe newer version of cargo causes this.

**Comment by nagy** [comment]
I use nixpkgs-unstable on all machines.

**Comment by Mic92** [comment]
I dropped `dog` some time ago. The version in nixpkgs should work.
