### ISSUE TITLE
Pandoc segfaults

### ISSUE THREAD

**Issue by doronbehar** [Mic92/nur-packages#3]
Continuing from your comment in https://github.com/NixOS/nixpkgs/issues/34376#issuecomment-585161829, I've tried to install pandoc from here and I got the segfault. Is it supposed to be updated? I'm using this:

```nix
  packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };
```

In my `~/.config/nixpkgs/config.nix`. Does the NUR repo gets updated only every few hours or so?

**Comment by Mic92** [comment]
Test again: https://github.com/nix-community/NUR/commit/5c1e370a35ec72fa10b9d12de56256b4fdc254cb
Also note that nix caches tarballs like the one from NUR. A nix garbage collect helps.

**Comment by doronbehar** [comment]
Fixed :).
